{% set version = '0.4.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-causact
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/causact_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/causact/causact_{{ version }}.tar.gz
  sha256: 60a65a0f831eaa401ee6fe404baa1a36ed6864199c23a944f50bb67b30383a15

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-diagrammer >=1.0.7
    - r-coda >=0.19.3
    - r-cowplot >=1.0.0
    - r-dplyr >=0.8.5
    - r-forcats >=0.5.0
    - r-ggplot2 >=3.3.0
    - r-greta >=0.3.1
    - r-htmlwidgets >=1.5.1
    - r-igraph >=1.2.5
    - r-lifecycle
    - r-magrittr >=1.5
    - r-purrr >=0.3.4
    - r-rlang >=0.4.6
    - r-rstudioapi >=0.11
    - r-stringr >=1.4.0
    - r-tidyr >=1.0.3

  run:
    - r-base
    - r-diagrammer >=1.0.7
    - r-coda >=0.19.3
    - r-cowplot >=1.0.0
    - r-dplyr >=0.8.5
    - r-forcats >=0.5.0
    - r-ggplot2 >=3.3.0
    - r-greta >=0.3.1
    - r-htmlwidgets >=1.5.1
    - r-igraph >=1.2.5
    - r-lifecycle
    - r-magrittr >=1.5
    - r-purrr >=0.3.4
    - r-rlang >=0.4.6
    - r-rstudioapi >=0.11
    - r-stringr >=1.4.0
    - r-tidyr >=1.0.3

test:
  commands:
    - $R -e "library('causact')"           # [not win]
    - "\"%R%\" -e \"library('causact')\""  # [win]

about:
  home: https://github.com/flyaflya/causact, https://www.causact.com/
  license: MIT
  summary: 'Accelerate Bayesian analytics workflows in ''R'' through interactive modelling, visualization,
    and inference. Define probabilistic graphical models using directed acyclic graphs
    (DAGs) as a unifying language for business stakeholders, statisticians, and programmers.
    This package relies on the sleek and elegant ''greta'' package for Bayesian inference.
    ''greta'', in turn, is an interface into ''TensorFlow'' from ''R''. Install ''greta''
    using instructions available here: <https://www.causact.com/install-tensorflow-greta-and-causact.html>.
    See <https://github.com/flyaflya/causact> or <https://www.causact.com/> for more
    documentation.'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# The original CRAN metadata for this package was:

# Package: causact
# Type: Package
# Title: Accelerated Bayesian Analytics with DAGs
# Version: 0.4.2
# Authors@R: c(person("Adam", "Fleischhacker", email = "ajf@udel.edu", role = c("aut", "cre","cph")), person("Daniela", "Dapena", role = "ctb"), person("Rose", "Nguyen", role = "ctb"), person("Jared", "Sharpe", role = "ctb") )
# Description: Accelerate Bayesian analytics workflows in 'R' through interactive modelling, visualization, and inference. Define probabilistic graphical models using directed acyclic graphs (DAGs) as a unifying language for business stakeholders, statisticians, and programmers. This package relies on the sleek and elegant 'greta' package for Bayesian inference. 'greta', in turn, is an interface into 'TensorFlow' from 'R'. Install 'greta' using instructions available here: <https://www.causact.com/install-tensorflow-greta-and-causact.html>. See <https://github.com/flyaflya/causact> or <https://www.causact.com/> for more documentation.
# License: MIT + file LICENSE
# URL: https://github.com/flyaflya/causact, https://www.causact.com/
# BugReports: https://github.com/flyaflya/causact/issues
# SystemRequirements: Python and TensorFlow are needed for Bayesian inference computations; Python (>= 2.7.0) with header files and shared library; TensorFlow (= v1.14; https://www.tensorflow.org/); TensorFlow Probability (= v0.7.0; https://www.tensorflow.org/probability/)
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.2.0)
# Imports: DiagrammeR (>= 1.0.7), dplyr (>= 0.8.5), magrittr (>= 1.5), ggplot2 (>= 3.3.0), rlang (>= 0.4.6), greta (>= 0.3.1), purrr (>= 0.3.4), tidyr (>= 1.0.3), igraph (>= 1.2.5), stringr (>= 1.4.0), cowplot (>= 1.0.0), coda (>= 0.19.3), forcats (>= 0.5.0), htmlwidgets (>= 1.5.1), rstudioapi (>= 0.11), lifecycle
# RoxygenNote: 7.1.2
# Suggests: knitr, covr, testthat (>= 3.0.0), rmarkdown
# Config/testthat/edition: 3
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2022-06-14 15:39:13 UTC; ajf
# Author: Adam Fleischhacker [aut, cre, cph], Daniela Dapena [ctb], Rose Nguyen [ctb], Jared Sharpe [ctb]
# Maintainer: Adam Fleischhacker <ajf@udel.edu>
# Repository: CRAN
# Date/Publication: 2022-06-14 16:00:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
